site_name: FASTlearn
plugins:
  # mermaid2
  - awesome-pages
  - table-reader
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      js_files:
        - load/javascripts/mermaid/mermaid.js
      css_files:
        - load/fonts/stylesheet.css
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      type: iso_datetime
  - tags:
      tags_file: art/tags.md
  - search:
      lang:
        - en
        - ja
      separator: '[\s\u200b\-]'
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
theme:
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides
  features:
    - search.suggest
    - search.highlight
    - navigation.tracking
    - navigation.instant
    # navigation.top
    - navigation.expand
    - navigation.sections
    # toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
  font: false
  palette:
    - scheme: default
      primary: white
      accent: amber
      toggle:
        icon: material/lightbulb
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/lightbulb-outline
  name: material
  language: zh
extra:
  cusdis:
    host: https://cus-fastlearn.xf-yun.cn
    app_id: 23b1a81c-8dc3-4240-bf28-97bb978454e1
    lang: zh-cn
  alternate:
    - name: 中文
      link: /zh/
      lang: zh
    - name: English
      link: /en/
      lang: en
extra_javascript:
  # load/javascripts/mermaid/mermaid-lad.js
  - load/javascripts/mermaid/mermaid.js
  - load/javascripts/katex/onload.js
  - load/javascripts/katex/contrib/auto-render.min.js
  - load/javascripts/katex/katex.min.js
  - load/javascripts/katex/contrib/mhchem.min.js
  # load/javascripts/mathjax.js
  # load/javascripts/polyfill.min.js?features=es6
  # load/javascripts/es5/tex-mml-chtml.js
  # load/javascripts/es5/tex-chtml-full.js
  # load/javascripts/es5/tex-svg-full.js
  # load/javascripts/es5/tex-mml-svg.js
extra_css:
  - load/javascripts/katex/katex.min.css
  - load/fonts/stylesheet.css
nav:
  - 哲学: art/about.md
  - 标签: art/tags.md
  - 数学:
      - 速查:
          - art/mat/formula/inequality.md
          - art/mat/formula/log.md
          - art/mat/formula/trigonometric.md
          - art/mat/formula/complex.md
          - art/mat/formula/vector.md
          - art/mat/formula/space.md
          - art/mat/formula/probability.md
  - 英语:
      - "文章":
          - "art/eng/articles/Secretary Blinken outlines the Administration’s policy toward the People’s Republic of China.md"
          - art/eng/articles/moon50.md
      - "新闻":
          - art/eng/archive-news/PSSMDAOGBGIHI.md
  - 物理:
      - 必修二:
          - "抛体运动":
              - art/phy/2.1/index.md
              - art/phy/2.1/2.1.1.md
              - art/phy/2.1/2.1.2.md
              - art/phy/2.1/2.1.4.md
              - art/phy/2.1/2.1.5.md
              - art/phy/2.1/2.1.6.md
          - "圆周运动":
              - art/phy/2.2/index.md
              - art/phy/2.2/2.2.1.md
              - art/phy/2.2/2.2.2.1.md
              - art/phy/2.2/2.2.2.2.md
              - art/phy/2.2/2.2.3.md
              - art/phy/2.2/2.2.4.md
          - "万有引力定律":
              - art/phy/2.3/index.md
              - 开普勒定律: art/phy/2.3/2.3.1.md
              - art/phy/2.3/2.3.2.md
              - art/phy/2.3/2.3.3.md
              - art/phy/2.3/2.3.4.md
          - "机械能及其守恒定律":
              - art/phy/2.4/index.md
              - art/phy/2.4/2.4.1.md
              - art/phy/2.4/2.4.2.md
              - art/phy/2.4/2.4.3.md
              - art/phy/2.4/2.4.4.md
              - art/phy/2.4/2.4.5.md
      - 必修三:
          - "静电场的描述":
              - art/phy/3.1/index.md
              - art/phy/3.1/3.1.1.md
              - art/phy/3.1/3.1.2.md
              - art/phy/3.1/3.1.3.md
              - art/phy/3.1/3.1.4.md
          - "静电场的应用":
              - art/phy/3.2/index.md
              - art/phy/3.2/3.2.1.md
              - art/phy/3.2/3.2.2.md
              - art/phy/3.2/3.2.3.md
          - 恒定电流:
              - art/phy/3.3/index.md
              - art/phy/3.3/3.3.1.md
              - art/phy/3.3/3.3.2.md
              - art/phy/3.3/3.3.3.md
      - 选择性必修一:
          - "动量守恒定律":
              - art/phy/4.1/index.md
              - art/phy/4.1/4.1.1.md
              - art/phy/4.1/4.1.2.md
  - 政治:
      - 必修三:
          - 中国共产党的领导:
              - art/pol/3.1/3.1.md
              - art/pol/3.1/3.1.1.md
              - art/pol/3.1/3.1.2.md
              - art/pol/3.1/3.1.3.md
      - 必修四:
          - 探索世界与把握规律:
              - art/pol/4.1/4.1.md
              - art/pol/4.1/4.1.1.md
              - art/pol/4.1/4.1.3.md
              - art/pol/4.1/4.1.4.md
              - art/pol/4.1/4.1.5.md
              - art/pol/4.1/4.1.6.md
              - art/pol/4.1/4.1.7.md
              - art/pol/4.1/4.1.8.md
repo_url: https://github.com/Github-DVIA/FASTlearn
repo_name: Edit on Github
copyright: 本项目没有许可证
site_author: ""
edit_uri: ""
