site_name: FASTlearn
markdown_extensions:
    - admonition
theme:
    name: readthedocs
    locale : zh_CN
nav:
    - 政治 :
        - 必修三 :
            - 第一单元 : pol/3.1.md
        - 必修四 :
            - 第一单元 : pol/4.1.md