site_name: FASTlearn
plugins:
  - git-revision-date
  - tags:
      tags_file: art/tags.md
  - search:
      lang:
        - en
        - ja
      separator: '[\s\u200b\-]'
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - extra
  - tables
  - smarty
  - toc:
      permalink: true
theme:
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.top
    - navigation.expand
    - navigation.sections
    # toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  name: material
  logo: load/logo/LOGO.png
  favicon: load/logo/LOGO.png
  font: false
  locale: zh_CN
  language: zh
extra_javascript:
  - load/javascripts/mathjax.js
  - load/javascripts/polyfill.min.js?features=es6
  - load/javascripts/es5/tex-mml-chtml.js
nav:
  - 主页: index.md
  - 标签: art/tags.md
  - 英语:
      - "文章":
          - "肯尼迪登月演讲": art/eng/articles/moon50.md
      - "新闻":
          - "纽约时报 2022.6.6": art/eng/archive-news/PSSMDAOGBGIHI.md
  - 物理:
      - 必修三:
          - "静电场的描述": art/phy/3.1.md
  - 政治:
      - 必修三:
          - "中国共产党的领导": art/pol/3.1.md
          - "人民当家作主": art/pol/3.2.md
          - "全面依法治国": art/pol/3.3.md
      - 必修四:
          - "探索世界和把握规律": art/pol/4.1.md
          - "认识社会和价值选择": art/pol/4.2.md
          - "文化传承和文化创新": art/pol/4.3.md
  - 帮助: 
      - "向导": help/guide.md
repo_url: https://github.com/Github-DVIA/FASTlearn
repo_name: Github-DVIA/FASTlearn
site_author: You!
copyright: Copyright &copy; 1911 - Now SDYZ
edit_uri: ""
