site_name: FASTlearn
markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - attr_list
    - def_list
theme:
    name: readthedocs
nav:
    - 政治 :
        - 必修三 :
            - 第一单元 : pol/3.1.md
        - 必修四 :
            - 第一单元 : pol/4.1.md