site_name: FASTlearn
plugins:
  - git-revision-date
  - tags:
      tags_file: art/tags.md
  - search:
      lang:
        - en
        - ja
      separator: '[\s\u200b\-]'
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - extra
  - tables
  - smarty
  - toc:
      permalink: true
theme:
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.top
    - navigation.expand
    - navigation.sections
    # toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
  font:
    code: Microsoft YaHei Mono
    text: Noto Sans
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: 切换到暗黑模式
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换到明亮模式
  name: material
  logo: load/logo/LOGO.png
  favicon: load/logo/LOGO.png
  font: false
  locale: zh_CN
  language: zh
extra_javascript:
  - load/javascripts/mathjax.js
  - load/javascripts/polyfill.min.js?features=es6
  - load/javascripts/es5/tex-mml-chtml.js
extra_css:
  - load/fonts/stylesheet.css
nav:
  - 主页: index.md
  - 标签: art/tags.md
  - 英语:
      - "文章":
          - "肯尼迪登月演讲": art/eng/articles/moon50.md
      - "新闻":
          - "纽约时报 2022.6.6": art/eng/archive-news/PSSMDAOGBGIHI.md
  - 数学:
      - 公式速查: 
          - 平面向量: art/mat/formula/vector.md
          - 复数: art/mat/formula/complex.md
          - art/mat/formula/trigonometric.md
  - 物理:
      - 必修三:
          - "静电场的描述": 
            - art/phy/3.1/3.1.md
            - '静电现象': art/phy/3.1/3.1.1.md
            - '静电力': art/phy/3.1/3.1.2.md
            - '电场': art/phy/3.1/3.1.3.md
            - '电势': art/phy/3.1/3.1.4.md
          - "静电场的应用": 
            - art/phy/3.2/3.2.md
            - art/phy/3.2/3.2.1.md
            - art/phy/3.2/3.2.2.md
  - 政治:
      - 必修三:
          - "中国共产党的领导": art/pol/3.1.md
          - "人民当家作主": art/pol/3.2.md
          - "全面依法治国": art/pol/3.3.md
      - 必修四:
          - "探索世界和把握规律": art/pol/4.1.md
          - "认识社会和价值选择": art/pol/4.2.md
          - "文化传承和文化创新": art/pol/4.3.md
  - 帮助: 
      - "向导": art/help/guide.md
repo_url: https://github.com/Github-DVIA/FASTlearn
repo_name: Github-DVIA/FASTlearn
site_author: DVIA
copyright: 欢迎转载，欢迎提交。难免有误，开题探究。
edit_uri: ""
