site_name: FASTlearn
plugins:
  # mermaid2
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      type: iso_datetime
  - search:
      lang:
        - en
        - ja
      separator: '[\s\u200b\-]'
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
  - md_in_html
  - abbr
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.smartsymbols
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.arithmatex:
      generic: true
  - admonition
  # extra
  - tables
  - smarty
  - meta
theme:
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides
  features:
    - search.suggest
    - search.highlight
    - navigation.tracking
    - navigation.instant
    # navigation.top
    - navigation.expand
    - navigation.sections
    # toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
  font: false
  palette:
    - scheme: default
      primary: white
      accent: amber
      toggle:
        icon: material/lightbulb
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/lightbulb-outline
  name: material
  language: zh
extra:
  cusdis:
    host: https://cus-fastlearn.xf-yun.cn
    app_id: 23b1a81c-8dc3-4240-bf28-97bb978454e1
    lang: zh-cn
extra_javascript:
  # load/javascripts/mermaid/mermaid-lad.js
  - load/javascripts/mermaid/mermaid.js
  - load/javascripts/katex/onload.js
  - load/javascripts/katex/contrib/auto-render.min.js
  - load/javascripts/katex/katex.min.js
  - load/javascripts/katex/contrib/mhchem.min.js
  # load/javascripts/mathjax.js
  # load/javascripts/polyfill.min.js?features=es6
  # load/javascripts/es5/tex-mml-chtml.js
  # load/javascripts/es5/tex-chtml-full.js
  # load/javascripts/es5/tex-svg-full.js
  # load/javascripts/es5/tex-mml-svg.js
extra_css:
  - load/javascripts/katex/katex.min.css
  - load/fonts/stylesheet.css
nav:
  - index.html
repo_url: https://github.com/Github-DVIA/FASTlearn
repo_name: Edit on Github
site_author: ""
edit_uri: ""
