site_name: FASTlearn
plugins:
  - git-revision-date
  - tags:
      tags_file: tags.md
  - search:
      lang:
        - en
        - ja
      separator: '[\s\u200b\-]'
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - extra
  - tables
  - smarty
  - toc:
      permalink: true
theme:
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.top
    - navigation.expand
    - navigation.sections
    # toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  name: material
  logo: logo/LOGO.png
  favicon: logo/LOGO.png
  font: false
  locale: zh_CN
  language: zh
extra_javascript:
  - javascripts/mathjax.js
  - javascripts/polyfill.min.js?features=es6
  - javascripts/es5/tex-mml-chtml.js
nav:
  - 主页: index.md
  - 标签: tags.md
  - 英语:
      - "新闻存档":
          - "NY-22.6.6": eng/archive-news/PSSMDAOGBGIHI.md
  - 物理:
      - 必修三:
          - "静电场的描述": phy/3.1.md
  - 政治:
      - 必修三:
          - "中国共产党的领导": pol/3.1.md
          - "人民当家作主": pol/3.2.md
          - "全面依法治国": pol/3.3.md
      - 必修四:
          - "探索世界和把握规律": pol/4.1.md
          - "认识社会和价值选择": pol/4.2.md
          - "文化传承和文化创新": pol/4.3.md
repo_url: https://github.com/Github-DVIA/FASTlearn
repo_name: Github-DVIA/FASTlearn
copyright: Copyright &copy; 2008 - Now DVIA
edit_uri: ""
