site_name: FASTlearn
markdown_extensions:
    - admonition
    - extra
    - smarty
    - toc
theme:
    name: readthedocs
    locale : zh_CN
nav:
    - 主页 : index.md
    - 政治 :
        - 必修三 :
            - '3.1 中国共产党的领导' : pol/3.1.md
        - 必修四 :
            - '4.1 探索世界与把握规律' : pol/4.1.md