name: gh-en
on:
  push:
    branches:
      - main-en
jobs:
  MakeSite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to main-en
        uses: actions/checkout@v3
        with:
          ref: "main-en"
          fetch-depth: "0"
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Build website
        run: mkdocs build
      - run: cd site && mkdir .github && cd .github && mkdir workflows
      - run: cd site/.github/workflows/ && curl -o main.yml "https://raw.githubusercontent.com/Github-DVIA/FASTlearn/master/.github/workflows/main.yml" && ls -a
      - name: Deploy to gh-en
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site
          branch: gh-en
          force: true
